# Generated by Django 3.1.7 on 2021-02-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taco4AEdicao2011',
            fields=[
                ('id', models.TextField(blank=True, db_column='id', primary_key=True, serialize=False)),
                ('nomedoalimento', models.TextField(blank=True, db_column='NomedoAlimento', null=True)),
                ('categoria', models.TextField(blank=True, db_column='Categoria', null=True)),
                ('umidade_field', models.TextField(blank=True, db_column='Umidade(%)', null=True)),
                ('energia_kcal_field', models.TextField(blank=True, db_column='Energia(kcal)', null=True)),
                ('energia_kj_field', models.TextField(blank=True, db_column='Energia(kJ)', null=True)),
                ('proteina_g_field', models.TextField(blank=True, db_column='Proteina(g)', null=True)),
                ('lipideos_g_field', models.TextField(blank=True, db_column='Lipideos(g)', null=True)),
                ('colesterol_mg_field', models.TextField(blank=True, db_column='Colesterol(mg)', null=True)),
                ('carboidrato_g_field', models.TextField(blank=True, db_column='Carboidrato(g)', null=True)),
                ('fibraalimentar_g_field', models.TextField(blank=True, db_column='FibraAlimentar(g)', null=True)),
                ('cinzas_g_field', models.TextField(blank=True, db_column='Cinzas(g)', null=True)),
                ('calcio_mg_field', models.TextField(blank=True, db_column='Calcio(mg)', null=True)),
                ('magnesio_mg_field', models.TextField(blank=True, db_column='Magnesio(mg)', null=True)),
                ('manganes_mg_field', models.TextField(blank=True, db_column='Manganes(mg)', null=True)),
                ('fosforo_mg_field', models.TextField(blank=True, db_column='Fosforo(mg)', null=True)),
                ('ferro_mg_field', models.TextField(blank=True, db_column='Ferro(mg)', null=True)),
                ('sodio_mg_field', models.TextField(blank=True, db_column='Sodio(mg)', null=True)),
                ('potassio_mg_field', models.TextField(blank=True, db_column='Potassio(mg)', null=True)),
                ('cobre_mg_field', models.TextField(blank=True, db_column='Cobre(mg)', null=True)),
                ('zinco_mg_field', models.TextField(blank=True, db_column='Zinco(mg)', null=True)),
                ('retinol_mg_field', models.TextField(blank=True, db_column='Retinol(mg)', null=True)),
                ('re_mcg_field', models.TextField(blank=True, db_column='RE(mcg)', null=True)),
                ('rae_mcg_field', models.TextField(blank=True, db_column='RAE(mcg)', null=True)),
                ('tiamina_mg_field', models.TextField(blank=True, db_column='Tiamina(mg)', null=True)),
                ('riboflavina_mg_field', models.TextField(blank=True, db_column='Riboflavina(mg)', null=True)),
                ('piridoxina_mg_field', models.TextField(blank=True, db_column='Piridoxina(mg)', null=True)),
                ('niacina_mg_field', models.TextField(blank=True, db_column='Niacina(mg)', null=True)),
                ('vitaminac_mg_field', models.TextField(blank=True, db_column='VitaminaC(mg)', null=True)),
            ],
            options={
                'db_table': 'Taco_4a_edicao_2011',
                'managed': False,
            },
        ),
    ]
